server:
  port: 9091

spring:
  application:
    name: Spring-MVC

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spring_mvc}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Pgsql#321}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp